# Generated by Django 4.0.4 on 2023-04-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppcampaignbank',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ppcampaignpointsbreakdown',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ppdrivercurrent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ppdriverhistorical',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ppdriverlevel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ppdriverpoints',
            options={},
        ),
    ]
