# Generated by Django 4.0.4 on 2023-04-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0003_alter_ppcampaignbank_options_ppcampaignbank_campaign_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppcampaignbank',
            options={},
        ),
    ]
