# Generated by Django 4.0.4 on 2023-05-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0004_alter_ppcampaignbank_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppdriverpoints',
            name='club_region',
        ),
        migrations.RemoveField(
            model_name='ppdriverpoints',
            name='territory',
        ),
    ]
