# Generated by Django 4.0.4 on 2023-05-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0005_remove_ppdriverpoints_club_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppcampaignpointsbreakdown',
            name='employee',
        ),
    ]
