# Generated by Django 4.0.4 on 2023-05-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0007_ppcampaignpointsbreakdown_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppcampaignpointsbreakdown',
            name='campaign',
        ),
    ]
