# Generated by Django 4.0.4 on 2023-05-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0009_ppcampaignpointsbreakdown_campaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppcampaignpointsbreakdown',
            options={'managed': False},
        ),
    ]
