# Generated by Django 4.0.4 on 2023-05-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0011_campaignregistrationstatusview2023_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppcampaignbanktransactionlog',
            name='overall_sat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppcampaignbanktransactionlog',
            name='overall_sat_threshold',
            field=models.BooleanField(default=False),
        ),
    ]
