# Generated by Django 4.0.4 on 2023-05-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0012_ppcampaignbanktransactionlog_overall_sat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppcampaignbank',
            options={'managed': False},
        ),
    ]
