# Generated by Django 4.0.4 on 2023-05-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0012_ppcampaignbanktransactionlog_overall_sat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppcampaignbanktransactionlog',
            name='totally_satisfied_count',
            field=models.IntegerField(default=0),
        ),
    ]
