# Generated by Django 4.0.4 on 2023-07-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0013_alter_ppcampaignbank_options'),
        ('performance_points', '0013_ppcampaignbanktransactionlog_totally_satisfied_count'),
    ]

    operations = [
    ]
