# Generated by Django 4.0.4 on 2023-07-17 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0014_merge_20230717_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppcampaign',
            name='tremendousCampaign',
        ),
        migrations.RemoveField(
            model_name='ppcampaignbanktransactionlog',
            name='paymentLog',
        ),
        migrations.CreateModel(
            name='PPCampaignPaymentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.DateField(blank=True, null=True)),
                ('cutoff', models.DateField(blank=True, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performance_points.ppcampaign')),
            ],
        ),
    ]
