# Generated by Django 4.0.4 on 2024-12-14 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_mtk_job_improvement_survey_mtk_job_improvements'),
        ('performance_points', '0016_springup2024drivertable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPCampaignDriverMetricTrackingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('overall_sat', models.FloatField(blank=True, null=True)),
                ('call_volume', models.IntegerField(blank=True, null=True)),
                ('logins', models.IntegerField(blank=True, null=True)),
                ('completed_clips', models.IntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_metric_tracking_campaign', to='performance_points.ppcampaign')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_metric_tracking_employee', to='accounts.employee')),
            ],
        ),
    ]
