# Generated by Django 4.0.4 on 2024-12-20 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0017_ppcampaign_show_performance_metrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='performance_points.ppcampaign')),
            ],
        ),
    ]
