# Generated by Django 4.0.4 on 2024-12-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0018_ppcampaign_display_end_ppcampaign_display_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppcampaign',
            name='confirmation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppcampaign',
            name='display_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppcampaign',
            name='display_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppcampaign',
            name='footnotes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ppcampaign',
            name='show_performance_metrics',
            field=models.BooleanField(default=False),
        ),
    ]
