# Generated by Django 2.1.4 on 2021-06-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_mobileappversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_budget', to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('GIFT_CARD', 'GIFT_CARD'), ('TREMENDOUS_API', 'TREMENDOUS_API')], default='TREMENDOUS_API', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_amount', models.FloatField(default=0)),
                ('payment_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_from', to='accounts.Employee')),
                ('payment_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_to', to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TremendousCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tremendous_id', models.CharField(max_length=255)),
                ('tremendous_funding_source_id', models.CharField(max_length=255)),
                ('total_budget', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='tremendous_campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_log_tremendous_campaign', to='payments.TremendousCampaign'),
        ),
        migrations.AddField(
            model_name='managerbudget',
            name='tremendous_campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_budget_tremendous_campaign', to='payments.TremendousCampaign'),
        ),
    ]
