# Generated by Django 2.1.4 on 2021-06-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('TREMENDOUS_API', 'TREMENDOUS_API'), ('GIFT_CARD', 'GIFT_CARD')], default='TREMENDOUS_API', max_length=255),
        ),
    ]
