# Generated by Django 4.0.4 on 2022-11-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210826_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('TREMENDOUS_API', 'TREMENDOUS_API'), ('GIFT_CARD', 'GIFT_CARD')], default='TREMENDOUS_API', max_length=255),
        ),
    ]
