# Generated by Django 4.0.4 on 2022-11-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentlog_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('GIFT_CARD', 'GIFT_CARD'), ('TREMENDOUS_API', 'TREMENDOUS_API')], default='TREMENDOUS_API', max_length=255),
        ),
    ]
