# Generated by Django 4.0.4 on 2023-04-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_reviewdriver_reviewquestion_transactioncampaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('WINGSPAN_API', 'WINGSPAN_API'), ('GIFT_CARD', 'GIFT_CARD')], default='TREMENDOUS_API', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('OTHER', 'OTHER'), ('MYSTERY SHOP', 'MYSTERY SHOP'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('DROPDOWN', 'DROPDOWN'), ('YES_NO', 'YES_NO'), ('MULTIPLE_CHOICE', 'MULTIPLE_CHOICE'), ('TEXTFIELD', 'TEXTFIELD')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='payment_method',
            field=models.CharField(choices=[('WINGSPAN_API', 'WINGSPAN_API'), ('GIFT_CARD', 'GIFT_CARD')], default='WINGSPAN_API', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('OTHER', 'OTHER'), ('MYSTERY SHOP', 'MYSTERY SHOP'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON')], max_length=255, null=True),
        ),
    ]
