# Generated by Django 4.0.4 on 2023-04-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_reviewdriver_reviewquestion_transactioncampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wingspanuseremployee',
            name='completed_w9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('MYSTERY SHOP', 'MYSTERY SHOP'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON'), ('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('OTHER', 'OTHER')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('TEXTFIELD', 'TEXTFIELD'), ('YES_NO', 'YES_NO'), ('DROPDOWN', 'DROPDOWN'), ('MULTIPLE_CHOICE', 'MULTIPLE_CHOICE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('MYSTERY SHOP', 'MYSTERY SHOP'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON'), ('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('OTHER', 'OTHER')], max_length=255, null=True),
        ),
    ]
