# Generated by Django 4.0.4 on 2023-05-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_paymentlog_payment_method_and_more'),
        ('payments', '0008_wingspanuseremployee_completed_w9_and_more'),
    ]

    operations = [
    ]
