# Generated by Django 4.0.4 on 2023-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_merge_20230517_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('DROPDOWN', 'DROPDOWN'), ('TEXTFIELD', 'TEXTFIELD'), ('YES_NO', 'YES_NO'), ('MULTIPLE_CHOICE', 'MULTIPLE_CHOICE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON')], max_length=255, null=True),
        ),
    ]
