# Generated by Django 4.0.4 on 2023-07-17 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0015_remove_ppcampaign_tremendouscampaign_and_more'),
        ('payments', '0012_alter_paymentlog_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpaymentlog',
            name='pp_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_points_campaign', to='performance_points.ppcampaign'),
        ),
        migrations.AddField(
            model_name='transactionpaymentlog',
            name='pp_campaign_pay_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_points_campaign_pay_period', to='performance_points.ppcampaignpaymentperiod'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('WINGSPAN_API', 'WINGSPAN_API'), ('GIFT_CARD', 'GIFT_CARD')], default='TREMENDOUS_API', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER'), ('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('DROPDOWN', 'DROPDOWN'), ('MULTIPLE_CHOICE', 'MULTIPLE_CHOICE'), ('TEXTFIELD', 'TEXTFIELD'), ('YES_NO', 'YES_NO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='payment_method',
            field=models.CharField(choices=[('WINGSPAN_API', 'WINGSPAN_API'), ('GIFT_CARD', 'GIFT_CARD')], default='WINGSPAN_API', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER'), ('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON')], max_length=255, null=True),
        ),
    ]
