# Generated by Django 4.0.4 on 2024-06-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_paymentlog_reason_alter_reviewquestion_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON'), ('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('YES_NO', 'YES_NO'), ('MULTIPLE_CHOICE', 'MULTIPLE_CHOICE'), ('DROPDOWN', 'DROPDOWN'), ('TEXTFIELD', 'TEXTFIELD')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON'), ('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='WingSpanUserW9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateField()),
                ('wingspanUserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wingspan_driver', to='payments.wingspanuseremployee')),
            ],
        ),
    ]
