# Generated by Django 4.0.4 on 2024-07-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_paymentlog_reason_alter_reviewquestion_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON'), ('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('YES_NO', 'YES_NO'), ('MULTIPLE_CHOICE', 'MULTIPLE_CHOICE'), ('TEXTFIELD', 'TEXTFIELD'), ('DROPDOWN', 'DROPDOWN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON'), ('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wingspanuserw9',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
