# Generated by Django 4.0.4 on 2024-12-18 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_mtk_job_improvement_survey_mtk_job_improvements'),
        ('payments', '0022_alter_paymentlog_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('WINGSPAN_API', 'WINGSPAN_API'), ('GIFT_CARD', 'GIFT_CARD')], default='TREMENDOUS_API', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON'), ('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('TEXTFIELD', 'TEXTFIELD'), ('DROPDOWN', 'DROPDOWN'), ('YES_NO', 'YES_NO'), ('MULTIPLE_CHOICE', 'MULTIPLE_CHOICE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='payment_method',
            field=models.CharField(choices=[('WINGSPAN_API', 'WINGSPAN_API'), ('GIFT_CARD', 'GIFT_CARD')], default='WINGSPAN_API', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON'), ('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RaffleWinners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_won', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_winner', to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RaffleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffle_entry_campaign', to='performance_points.ppcampaign')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_entry', to='accounts.employee')),
            ],
        ),
    ]
