# Generated by Django 4.0.4 on 2024-12-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_paymentlog_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method',
            field=models.CharField(choices=[('GIFT_CARD', 'GIFT_CARD'), ('WINGSPAN_API', 'WINGSPAN_API')], default='TREMENDOUS_API', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON'), ('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='payment_method',
            field=models.CharField(choices=[('GIFT_CARD', 'GIFT_CARD'), ('WINGSPAN_API', 'WINGSPAN_API')], default='WINGSPAN_API', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionpaymentlog',
            name='reason',
            field=models.CharField(blank=True, choices=[('MYSTERY SHOP', 'MYSTERY SHOP'), ('OTHER', 'OTHER'), ('GREAT JOB - IN PERSON', 'GREAT JOB - IN PERSON'), ('GREAT JOB - REMOTE', 'GREAT JOB - REMOTE')], max_length=255, null=True),
        ),
    ]
