# Generated by Django 2.1.4 on 2021-06-23 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20210609_1656'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BigIntegerField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position_type', models.CharField(blank=True, max_length=255, null=True)),
                ('d3_login_id', models.CharField(blank=True, max_length=255, null=True)),
                ('no_login_id_match', models.BooleanField(null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('percent_complete', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_results_more',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.Campaign')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_order', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('html_text', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleMultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer_one', models.TextField(blank=True, null=True)),
                ('answer_two', models.TextField(blank=True, null=True)),
                ('answer_three', models.TextField(blank=True, null=True)),
                ('answer_four', models.TextField(blank=True, null=True)),
                ('answer_five', models.TextField(blank=True, null=True)),
                ('correct_answer', models.IntegerField(blank=True, null=True)),
                ('answer_explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('question_count', models.IntegerField(blank=True, null=True)),
                ('pass_threshold', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=255)),
                ('display_start', models.DateField(blank=True, null=True)),
                ('display_end', models.DateField(blank=True, null=True)),
                ('completed_list', models.ManyToManyField(to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingVideoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct', models.ManyToManyField(related_name='completed_and_correct', to='accounts.Employee')),
                ('incorrect', models.ManyToManyField(related_name='completed_and_incorrect', to='accounts.Employee')),
                ('video_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reference', to='training.TrainingVideo')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingViedoQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possible_answer', to='training.TrainingVideoQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=100)),
                ('doc_url', models.CharField(max_length=255)),
                ('doc_desc', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='documents/thumbnails/')),
                ('position_type', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_type', models.CharField(blank=True, choices=[('All', 'All'), ('CSN', 'CSN'), ('Fleet', 'Fleet')], max_length=255, null=True, verbose_name='Driver Type')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_questions', models.IntegerField(blank=True, null=True)),
                ('incorrect_questions', models.IntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('question_history', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('last_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_progress', to='training.ModuleFlow')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_progress', to='training.ModuleOverview')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userdocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.UserDocumentCategory'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Permissions'),
        ),
        migrations.AddField(
            model_name='modulemultiplechoice',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_multiple_choice', to='training.ModuleOverview'),
        ),
        migrations.AddField(
            model_name='moduleflow',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_module_flow', to='training.ModuleOverview'),
        ),
        migrations.AddField(
            model_name='moduleflow',
            name='multiple_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_module_flow', to='training.ModuleMultipleChoice'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.ModuleOverview'),
        ),
    ]
