# Generated by Django 4.0.4 on 2023-04-19 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_points', '0001_initial'),
        ('training', '0003_modulepage_modulequestion_moduletag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletag',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_module_tag', to='performance_points.ppcampaign'),
        ),
    ]
