# Generated by Django 4.0.4 on 2024-12-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_modulecompletion_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleoverview',
            name='tags',
        ),
    ]
