# Generated by Django 2.1.4 on 2021-04-20 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210311_0933'),
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRegistrationStatus',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('campaign_title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('driver_name', models.CharField(blank=True, db_column='full_name', max_length=255, null=True)),
                ('driver_id', models.IntegerField(db_column='driver_employee_id', null=True)),
                ('organization', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('territory', models.CharField(blank=True, db_column='territory', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_column='username', max_length=255, null=True)),
                ('date_joined', models.DateField(blank=True, db_column='date_joined', null=True)),
                ('last_login', models.DateField(blank=True, db_column='last_login', null=True)),
                ('is_registered', models.BooleanField(blank=True, db_column='is_registered', null=True)),
                ('registration_date', models.DateField(blank=True, db_column='registration_date', null=True)),
                ('cohort_name', models.CharField(blank=True, db_column='registration_cohort_name', max_length=255, null=True)),
                ('preferred_payment_method', models.CharField(blank=True, db_column='preferred_payment_method', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CampaignRegistrationStatusView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignEligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DriverCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('info_file', models.FileField(blank=True, null=True, upload_to='')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='App Notes')),
                ('rdb_site_notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('payment_converter', models.TextField(blank=True, null=True)),
                ('campaign_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena.CampaignType')),
                ('metrics', models.ManyToManyField(blank=True, to='arena.CampaignMetrics')),
            ],
        ),
        migrations.CreateModel(
            name='DriverCampaignExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='DriverCampaignRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena.DriverCampaign')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('already_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('payment_value', models.FloatField(blank=True, null=True)),
                ('upload_from_date', models.DateField(blank=True, null=True)),
                ('upload_to_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee')),
                ('driver_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena.DriverPayments')),
            ],
        ),
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_from_date', models.DateField(blank=True, null=True)),
                ('upload_to_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena.DriverCampaign')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Service event Start')),
                ('registration_start', models.DateTimeField(blank=True, help_text='The start date and time of this cohort. Anyone registering starting at this date and time will be placed on this cohort.', null=True)),
                ('end', models.DateTimeField(blank=True, help_text='Select the day after the last day of the registration with the time 00:00:00. This means anyone registered UP TO this date and time will be on this cohort.', null=True, verbose_name='Registration End Date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena.DriverCampaign')),
            ],
        ),
        migrations.AddField(
            model_name='driverpayments',
            name='pay_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena.PayPeriod'),
        ),
        migrations.AddField(
            model_name='driverpayments',
            name='registration_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena.RegistrationCohort'),
        ),
        migrations.AddField(
            model_name='drivercampaignregistration',
            name='registration_cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena.RegistrationCohort'),
        ),
        migrations.AddField(
            model_name='campaigneligibility',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arena.DriverCampaign'),
        ),
        migrations.AddField(
            model_name='campaigneligibility',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Organization'),
        ),
    ]
