# Generated by Django 2.1.4 on 2021-05-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_auto_20210420_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmetrics',
            name='annotate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='key_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='show_on_site_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drivercampaign',
            name='app_site_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivercampaign',
            name='pay_cap',
            field=models.IntegerField(db_column='pay_period_cap', default=10000),
        ),
        migrations.AddField(
            model_name='drivercampaign',
            name='rewards_bottom_slot_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_bottom_slot_metric', to='arena.CampaignMetrics'),
        ),
        migrations.AddField(
            model_name='drivercampaign',
            name='rewards_bottom_slot_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivercampaign',
            name='rewards_top_slot_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_top_slot_metric', to='arena.CampaignMetrics'),
        ),
        migrations.AddField(
            model_name='drivercampaign',
            name='rewards_top_slot_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivercampaign',
            name='show_rewards_bottom_slot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drivercampaign',
            name='show_rewards_top_slot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drivercampaign',
            name='site_metrics',
            field=models.ManyToManyField(blank=True, related_name='metrics_for_rdb_site', to='arena.CampaignMetrics', verbose_name='Metrics to display in the RDB site'),
        ),
        migrations.AlterField(
            model_name='drivercampaign',
            name='campaign_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_type', to='arena.CampaignType'),
        ),
        migrations.AlterField(
            model_name='drivercampaign',
            name='metrics',
            field=models.ManyToManyField(blank=True, related_name='metrics_for_app', to='arena.CampaignMetrics', verbose_name='Metrics needed for App'),
        ),
    ]
