# Generated by Django 2.1.4 on 2021-06-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_auto_20210517_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivercampaign',
            name='payout_converter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
