# Generated by Django 2.1.4 on 2021-06-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('arena', '0005_auto_20210604_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivercampaign',
            name='tremendous_campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tremendous_campaign', to='payments.TremendousCampaign'),
        ),
    ]
