# Generated by Django 2.1.4 on 2021-06-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0006_drivercampaign_tremendous_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercampaign',
            name='tremendous_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tremendous_campaign', to='payments.TremendousCampaign'),
        ),
    ]
