# Generated by Django 4.0.4 on 2023-07-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0007_auto_20210611_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivercampaign',
            name='tremendous_campaign',
        ),
    ]
