# Generated by Django 2.1.4 on 2021-04-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcements',
            name='platform',
            field=models.CharField(blank=True, choices=[('RDB Site', 'RDB Site'), ('App', 'App'), ('Global', 'Global')], max_length=255, null=True),
        ),
    ]
