# Generated by Django 2.1.4 on 2021-06-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_auto_20210517_0958'),
        ('messaging', '0003_auto_20210422_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='campaign_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_group', to='arena.DriverCampaign'),
        ),
    ]
