# Generated by Django 2.1.4 on 2021-06-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_announcements_campaign_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='position_types',
            field=models.CharField(blank=True, choices=[('everyone', 'everyone'), ('Admin', 'Admin'), ('Appeals-Access', 'Appeals-Access'), ('Driver', 'Driver'), ('Executive', 'Executive'), ('Facility-Rep', 'Facility-Rep'), ('Field-Rep', 'Field-Rep'), ('Fleet-Manager', 'Fleet-Manager'), ('Fleet-Supervisor', 'Fleet-Supervisor'), ('Project Manager', 'Project Manager'), ('Station-Admin', 'Station-Admin'), ('Territory-Associate', 'Territory-Associate')], default='everyone', max_length=255, null=True),
        ),
    ]
