# Generated by Django 2.1.4 on 2021-06-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20210623_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='target_by_facility_rep',
            field=models.ManyToManyField(blank=True, null=True, related_name='targeting_facility_rep', to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='target_by_station_business',
            field=models.ManyToManyField(blank=True, null=True, related_name='targeting_station_business', to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='target_by_station_states',
            field=models.ManyToManyField(blank=True, null=True, related_name='targeting_station_state', to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='target_by_stations',
            field=models.ManyToManyField(blank=True, null=True, related_name='targeting_stations', to='accounts.Organization'),
        ),
    ]
