# Generated by Django 2.1.4 on 2021-06-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210609_1656'),
        ('messaging', '0007_auto_20210623_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='target_by_stations',
        ),
        migrations.AddField(
            model_name='announcements',
            name='target_by_hubs',
            field=models.ManyToManyField(blank=True, null=True, related_name='targeting_hubs', to='accounts.Organization'),
        ),
    ]
