# Generated by Django 2.1.4 on 2021-08-26 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_auto_20210623_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='target_by_facility_rep',
            field=models.ManyToManyField(blank=True, related_name='targeting_facility_rep', to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='target_by_hubs',
            field=models.ManyToManyField(blank=True, related_name='targeting_hubs', to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='target_by_station_business',
            field=models.ManyToManyField(blank=True, related_name='targeting_station_business', to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='target_by_station_states',
            field=models.ManyToManyField(blank=True, related_name='targeting_station_state', to='accounts.Organization'),
        ),
    ]
