# Generated by Django 4.0.4 on 2023-02-14 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_stationdriver_options'),
        ('messaging', '0009_auto_20210826_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(default='Normal', max_length=100)),
                ('sent_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_auth', to='accounts.employee')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_parent', to='messaging.mailmessage')),
                ('recipient', models.ManyToManyField(to='accounts.employee')),
            ],
        ),
    ]
