# Generated by Django 4.0.4 on 2024-12-18 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_mailmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTKMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_message_title', models.CharField(blank=True, max_length=100, null=True)),
                ('inbox_message_text', models.TextField(blank=True, null=True)),
                ('banner_text', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_only', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('hierarchy', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('banner', 'banner'), ('inbox', 'inbox')], default='is-primary', max_length=255, null=True)),
                ('external_link', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_link', models.CharField(blank=True, max_length=255, null=True)),
                ('pp_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_message', to='performance_points.ppcampaign')),
            ],
        ),
    ]
