# Generated by Django 4.0.4 on 2024-12-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_mtkmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtkmessage',
            name='type',
            field=models.CharField(blank=True, choices=[('general', 'general'), ('raffle', 'raffle'), ('w9', 'w9'), ('registration', 'registration')], default='general', max_length=255, null=True),
        ),
    ]
