# Generated by Django 4.0.4 on 2024-12-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_alter_mtkmessage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtkmessage',
            name='button_text',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
