# Generated by Django 4.0.4 on 2024-12-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_mtkmessage_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtkmessage',
            name='button_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
