# Generated by Django 4.0.4 on 2024-12-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_alter_mtkmessage_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtkmessage',
            name='banner_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
