# Generated by Django 4.0.4 on 2024-12-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_alter_mtkmessage_internal_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtkmessage',
            name='internal_link',
            field=models.CharField(blank=True, choices=[('/campaigns', '/campaigns'), ('/payments_w9', '/payments_w9'), ('/training', '/training')], max_length=255, null=True),
        ),
    ]
