# Generated by Django 2.1.4 on 2021-03-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='parallel_organizations',
            field=models.ManyToManyField(related_name='employee_parallel_organization', to='accounts.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parallel_parent_stream',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='parallel_parents',
            field=models.ManyToManyField(related_name='_organization_parallel_parents_+', to='accounts.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employees_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_employees_under', to='accounts.Organization'),
        ),
    ]
