# Generated by Django 2.1.4 on 2021-05-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210311_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('current_release', models.BooleanField(default=False)),
                ('release_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
