# Generated by Django 2.1.4 on 2021-06-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mobileappversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parallel_parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='_organization_parallel_parents_+', to='accounts.Organization'),
        ),
    ]
