# Generated by Django 2.1.4 on 2021-06-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210609_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='parallel_organizations',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee_parallel_organization', to='accounts.Organization'),
        ),
    ]
