# Generated by Django 4.0.4 on 2023-02-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_employee_duplicate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationdriver',
            options={'managed': False},
        ),
    ]
