# Generated by Django 4.0.4 on 2023-04-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_stationdriver_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stationdriver',
            table='accounts_stationdriver_view',
        ),
    ]
