# Generated by Django 4.0.4 on 2023-04-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_moduletag_campaign'),
        ('accounts', '0011_alter_stationdriver_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='campaign_preferred_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_modules',
            field=models.ManyToManyField(related_name='completed_modules', to='training.moduleoverview'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
