# Generated by Django 4.0.4 on 2023-04-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_campaign_preferred_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='completed_modules',
        ),
    ]
