# Generated by Django 4.0.4 on 2023-04-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_moduletag_campaign'),
        ('accounts', '0013_remove_profile_completed_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_modules',
            field=models.ManyToManyField(related_name='completed_modules', to='training.moduleoverview'),
        ),
    ]
