# Generated by Django 4.0.4 on 2023-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_completed_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWageupEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('custom_url', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_button_label', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
