# Generated by Django 4.0.4 on 2023-05-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customwageupemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customwageupemail',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
