# Generated by Django 4.0.4 on 2023-10-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customwageupemail_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mtk_satisfaction', models.CharField(blank=True, max_length=255, null=True)),
                ('mtk_recommendation_likelihood', models.IntegerField(blank=True, null=True)),
                ('mtk_job_improvement', models.JSONField(blank=True, default=list)),
                ('mtk_usage_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('mtk_ease_of_use', models.CharField(blank=True, max_length=255, null=True)),
                ('mtk_importance', models.CharField(blank=True, max_length=255, null=True)),
                ('mtk_inspiration', models.CharField(blank=True, max_length=255)),
                ('mtk_improvement_response', models.CharField(blank=True, max_length=255)),
                ('mtk_testimonial', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey', to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EligibleDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_wageup_id', models.IntegerField(blank=True, null=True)),
                ('driver_aca_id', models.IntegerField(blank=True, null=True)),
                ('driver_org', models.CharField(blank=True, max_length=100, null=True)),
                ('territory', models.CharField(blank=True, max_length=50, null=True)),
                ('distributor', models.CharField(blank=True, max_length=100, null=True)),
                ('distributor_org', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
    ]
