# Generated by Django 4.0.4 on 2023-10-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_survey_eligibledriver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eligibledriver',
            old_name='driver_aca_id',
            new_name='driver_id',
        ),
        migrations.RemoveField(
            model_name='eligibledriver',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='eligibledriver',
            name='distributor_org',
        ),
        migrations.RemoveField(
            model_name='eligibledriver',
            name='driver_wageup_id',
        ),
        migrations.RemoveField(
            model_name='eligibledriver',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='eligibledriver',
            name='territory',
        ),
    ]
