# Generated by Django 2.1.4 on 2021-04-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210419_1211'),
    ]

    operations = [
        # migrations.AlterIndexTogether(
        #     name='std12eraw',
        #     index_together=set(),
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='emp_driver_id',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='emp_svc_facl_rep',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='fleet_supervisor',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='org_booth',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='org_business_id',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='org_call_center',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='org_call_center_group',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='org_club_region',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='org_grid',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='org_market_id',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='org_svc_facl_id',
        # ),
        # migrations.RemoveField(
        #     model_name='std12eraw',
        #     name='org_territory_id',
        # ),
        # migrations.AlterModelTable(
        #     name='rawops',
        #     table='raw_ops_copy',
        # ),
        # migrations.DeleteModel(
        #     name='Std12ERaw',
        # ),
    ]
