# Generated by Django 2.1.4 on 2021-04-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210420_1146'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='dashboardnew',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='dashboardnew',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='dashboardnew',
            name='organization',
        ),
        migrations.AlterIndexTogether(
            name='std12eraw',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='emp_driver_id',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='emp_svc_facl_rep',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='fleet_supervisor',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='org_booth',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='org_business_id',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='org_call_center',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='org_call_center_group',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='org_club_region',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='org_grid',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='org_market_id',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='org_svc_facl_id',
        ),
        migrations.RemoveField(
            model_name='std12eraw',
            name='org_territory_id',
        ),
        migrations.AddField(
            model_name='commentssurveyse',
            name='topics_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='dashboardaggregations',
            table='dashboard_aggregations',
        ),
        migrations.AlterModelTable(
            name='rawops',
            table='raw_ops_copy',
        ),
        migrations.DeleteModel(
            name='DashboardNew',
        ),
        migrations.DeleteModel(
            name='Std12ERaw',
        ),
    ]
