# Generated by Django 2.1.4 on 2021-04-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210421_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesschedule',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeseriesscheduletemplate',
            name='template_name',
            field=models.CharField(blank=True, default='Default', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='rawops',
            table='dashboard_rawops',
        ),
    ]
