# Generated by Django 2.1.4 on 2021-04-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210311_0933'),
        ('dashboard', '0005_auto_20210422_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='std12etiers',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_tier', to='accounts.Organization'),
        ),
    ]
