# Generated by Django 2.1.4 on 2021-06-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_std12etiers_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeseriesPredictionsOrgsPredicted',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('organization', models.IntegerField(db_column='organization_id')),
            ],
            options={
                'db_table': 'predicted_stations',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='std12etiers',
            options={'managed': False},
        ),
    ]
