# Generated by Django 2.1.4 on 2021-06-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210603_1520'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='std12etiers',
            table='dashboard_std12etiers2',
        ),
    ]
