# Generated by Django 2.1.4 on 2021-08-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210604_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriespredictionsbyhournew',
            name='total_drivers_wait_15',
            field=models.BigIntegerField(blank=True, db_column='total_drivers_wait_15', null=True),
        ),
    ]
