# Generated by Django 2.1.4 on 2021-09-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210623_1259'),
        ('dashboard', '0010_auto_20210902_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesscheduleddrivers',
            name='zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesscheduleddrivers',
            unique_together={('employee', 'schedule')},
        ),
    ]
