# Generated by Django 4.0.4 on 2023-04-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_dashboardannotation_directviews_metricgoals_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBatteryAggregations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_dt', models.DateField(db_column='SC_DT')),
                ('time_type', models.CharField(db_column='TIME_TYPE', max_length=255)),
                ('index_type', models.CharField(blank=True, db_column='INDEX_TYPE', max_length=255, null=True)),
                ('id_name_helper', models.CharField(blank=True, db_column='ID_NAME_HELPER', max_length=255, null=True)),
                ('parent_id', models.IntegerField(blank=True, db_column='PARENT_ID', null=True)),
                ('parent_name', models.CharField(blank=True, db_column='PARENT_NAME', max_length=255, null=True)),
                ('num_ops', models.FloatField(blank=True, db_column='NUM_OPS', null=True)),
                ('batt_truck_num', models.FloatField(blank=True, db_column='BATT_TRUCK_NUM', null=True)),
                ('batt_truk_avg', models.FloatField(blank=True, db_column='BATT_TRUK_PCNT', null=True)),
                ('matched_tests', models.FloatField(blank=True, db_column='MATCHED_TESTS', null=True)),
                ('test_rate_avg', models.FloatField(blank=True, db_column='TEST_RATE', null=True)),
                ('edocs_count', models.FloatField(blank=True, db_column='EDOCS_COUNT', null=True)),
                ('edocs_conv_avg', models.FloatField(blank=True, db_column='EDOCS_CONV_PCNT', null=True)),
                ('conv_to_fail_num', models.FloatField(blank=True, db_column='CONV_TO_FAIL_NUM', null=True)),
                ('conv_to_fail_denom', models.FloatField(blank=True, db_column='CONV_TO_FAIL_DENOM', null=True)),
                ('conv_to_fail', models.FloatField(blank=True, db_column='CONV_TO_FAIL', null=True)),
                ('edocs_denom', models.FloatField(blank=True, db_column='EDOCS_PCNT_DENOM', null=True)),
                ('edocs_avg', models.FloatField(blank=True, db_column='EDOCS_PCNT', null=True)),
                ('vin_count', models.FloatField(blank=True, db_column='VIN_COUNT', null=True)),
                ('vin_avg', models.FloatField(blank=True, db_column='VIN_PCNT', null=True)),
                ('date_updated', models.DateTimeField(blank=True, db_column='DATE_UPDATED', null=True)),
                ('paid_call_count', models.DecimalField(blank=True, db_column='PAID_CALL_COUNT', decimal_places=0, max_digits=25, null=True)),
                ('light_svc_volume', models.DecimalField(blank=True, db_column='LIGHT_SVC_VOLUME', decimal_places=0, max_digits=25, null=True)),
                ('ata_under_45_freq', models.DecimalField(blank=True, db_column='ATA_UNDER_45_FREQ', decimal_places=4, max_digits=7, null=True)),
                ('battery_volume', models.DecimalField(blank=True, db_column='BATTERY_VOLUME', decimal_places=0, max_digits=23, null=True)),
                ('battery_ata_avg', models.DecimalField(blank=True, db_column='BATTERY_OPP_ATA_AVG', decimal_places=4, max_digits=23, null=True)),
                ('battery_ata_sum', models.DecimalField(blank=True, db_column='BATTERY_OPP_ATA_SUM', decimal_places=4, max_digits=23, null=True)),
                ('battery_replacement_volume', models.DecimalField(blank=True, db_column='BATTERY_REPLACEMENT_VOLUME', decimal_places=0, max_digits=25, null=True)),
                ('battery_replacement_freq', models.DecimalField(blank=True, db_column='BATTERY_REPLACEMENT_FREQ', decimal_places=4, max_digits=23, null=True)),
                ('battery_ol_to_clr_avg', models.DecimalField(blank=True, db_column='BATTERY_OL_TO_CLR_AVG', decimal_places=4, max_digits=23, null=True)),
                ('battery_ol_to_clr_sum', models.DecimalField(blank=True, db_column='BATTERY_OL_TO_CLR_SUM', decimal_places=4, max_digits=23, null=True)),
                ('aaa_mgmt_battery_overall_sat_avg', models.FloatField(blank=True, db_column='AAA_MGMT_BATTERY_OVERALL_SAT_AVG', null=True)),
                ('aaa_mgmt_battery_overall_sat_count', models.BigIntegerField(blank=True, db_column='AAA_MGMT_BATTERY_OVERALL_SAT_COUNT', null=True)),
                ('aaa_mgmt_battery_overall_sat_sum', models.BigIntegerField(blank=True, db_column='AAA_MGMT_BATTERY_OVERALL_SAT_SUM', null=True)),
                ('comp_battery_overall_sat_avg', models.FloatField(blank=True, db_column='COMP_BATTERY_OVERALL_SAT_AVG', null=True)),
                ('comp_battery_overall_sat_count', models.BigIntegerField(blank=True, db_column='COMP_BATTERY_OVERALL_SAT_COUNT', null=True)),
                ('comp_battery_overall_sat_sum', models.BigIntegerField(blank=True, db_column='COMP_BATTERY_OVERALL_SAT_SUM', null=True)),
                ('approximate_battery_revenue', models.DecimalField(blank=True, db_column='APPROXIMATE_BATTERY_REVENUE', decimal_places=0, max_digits=25, null=True)),
            ],
            options={
                'db_table': 'dashboard_battery_aggregations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtlStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('today', models.BooleanField()),
                ('progress', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'etl_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawOpsAggSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_dt', models.DateField(db_column='SC_DT')),
                ('sc_id', models.IntegerField(db_column='SC_ID')),
                ('re_tm', models.DateTimeField(blank=True, db_column='RE_TM', null=True)),
                ('tcd', models.CharField(blank=True, db_column='TCD', max_length=20, null=True)),
                ('shift', models.CharField(blank=True, db_column='SHIFT', max_length=20, null=True)),
                ('ata', models.FloatField(blank=True, db_column='ATA', null=True)),
                ('pta', models.FloatField(blank=True, db_column='PTA', null=True)),
                ('reroute', models.BooleanField(null=True)),
                ('overall_sat', models.BooleanField(null=True)),
                ('facility_sat', models.BooleanField(null=True)),
                ('kept_informed_sat', models.BooleanField(null=True)),
                ('request_svc_sat', models.BooleanField(db_column='REQUEST_SERVICE_SAT', null=True)),
                ('response_sat', models.BooleanField(null=True)),
                ('date_updated_surveys', models.DateTimeField()),
            ],
            options={
                'db_table': 'tcd_calcs_stored',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='std12etiers',
            table='dashboard_std12etiers',
        ),
    ]
