# Generated by Django 2.1.4 on 2021-06-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20210609_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRemoveDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_id', models.CharField(blank=True, max_length=255, null=True)),
                ('multiple_id', models.BooleanField(blank=True, null=True)),
                ('shop_id_list', models.CharField(blank=True, max_length=255, null=True)),
                ('add_drivers', models.TextField(blank=True, null=True)),
                ('remove_drivers', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('open', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tm', models.CharField(blank=True, max_length=255, null=True)),
                ('point_of_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('open', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('grid_size', models.IntegerField(default=1)),
                ('title', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('announcementType', models.CharField(blank=True, max_length=225, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('url_link', models.CharField(blank=True, max_length=225, null=True)),
                ('type', models.CharField(default='simple', max_length=225)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee_groups', models.ManyToManyField(related_name='widget_group', to='accounts.EmployeeGroup')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetModalContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=225, null=True)),
                ('url_link', models.CharField(blank=True, max_length=225, null=True)),
                ('url_text', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('is_file', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='modal_content',
            field=models.ManyToManyField(related_name='modal_content', to='homepage.WidgetModalContent'),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='permissions',
            field=models.ManyToManyField(related_name='visible_for', to='accounts.Employee'),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='seen_by',
            field=models.ManyToManyField(related_name='widget_seen_by', to='accounts.Employee'),
        ),
        migrations.AddField(
            model_name='widgetdata',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widget_type', to='homepage.Widget'),
        ),
    ]
