# Generated by Django 2.1.4 on 2021-05-12 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210311_0933'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaUserTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.BigIntegerField(blank=True, db_column='Sessions', null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position_type', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_parent', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login', models.DateTimeField()),
                ('is_staff', models.BooleanField(null=True)),
                ('sat_app_logins', models.BigIntegerField(blank=True, db_column='sat_app_logins', null=True)),
                ('website_logins', models.BigIntegerField(blank=True, db_column='website_logins', null=True)),
            ],
            options={
                'db_table': 'ga_user_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('include', models.BooleanField(null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.ManyToManyField(to='onboarding.DemoContent')),
            ],
        ),
        migrations.CreateModel(
            name='Deployments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=255, null=True)),
                ('element_type', models.CharField(blank=True, max_length=255, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('number_type', models.CharField(blank=True, max_length=255, null=True)),
                ('highGood', models.BooleanField(null=True)),
                ('formatted_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_equation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enhancements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errorTracking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetricCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_parent', to='onboarding.MetricCategories')),
            ],
        ),
        migrations.CreateModel(
            name='UserDemoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_history', to='onboarding.DemoPage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documentation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_category', to='onboarding.MetricCategories'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='faq',
            field=models.ManyToManyField(blank=True, related_name='_documentation_faq_+', to='onboarding.Documentation'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='permission',
            field=models.ManyToManyField(blank=True, to='accounts.Permissions'),
        ),
        migrations.AddField(
            model_name='deployments',
            name='enhancements',
            field=models.ManyToManyField(blank=True, to='onboarding.Enhancements'),
        ),
    ]
