# Generated by Django 4.0.4 on 2022-11-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='faq',
            field=models.ManyToManyField(blank=True, to='onboarding.documentation'),
        ),
    ]
