# Generated by Django 4.0.4 on 2023-04-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_documentation_faq'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gausertracking',
            table='user_tracking_view',
        ),
    ]
